In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()

DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database(), current_user;"))
    for row in result:
        print(row)

('growthflow_db', 'postgres')

In [2]:
tables_query = """
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
ORDER BY table_schema, table_name;
"""

tables_df = pd.read_sql(tables_query, engine)
tables_df

  table_schema       table_name
0       public        customers
1       public  engagement_data
2       public    feedback_data
3       public    subscriptions
4       public       usage_data

In [3]:
pd.read_sql("SELECT * FROM customers LIMIT 5;", engine)

,customer_id,subscription_date,industry,region,customer_type,plan_type,company_size
0,CUST_00001,2024-04-12,Finance,Europe,Mid-market,Basic,171
1,CUST_00002,2025-04-11,Finance,Europe,SMB,Basic,24
2,CUST_00003,2024-05-10,Education,Latin America,SMB,Enterprise,2
3,CUST_00004,2024-07-10,Technology,Europe,Enterprise,Enterprise,3404
4,CUST_00005,2025-07-14,Education,Latin America,SMB,Basic,15

In [4]:
pd.read_sql("SELECT * FROM subscriptions LIMIT 5;", engine)

,subscription_id,customer_id,start_date,end_date,subscription_type,monthly_revenue,plan_type,customer_type,is_churned
0,1,CUST_00001,2024-04-12,2025-12-31,Monthly,49,Basic,Mid-market,0
1,2,CUST_00002,2025-04-11,2025-12-31,Annual,29,Basic,SMB,0
2,3,CUST_00003,2024-05-10,2025-11-01,Monthly,299,Enterprise,SMB,1
3,4,CUST_00004,2024-07-10,2025-12-31,Annual,999,Enterprise,Enterprise,0
4,5,CUST_00005,2025-07-14,2025-12-31,Monthly,29,Basic,SMB,1

In [5]:
pd.read_sql("SELECT * FROM usage_data LIMIT 5;", engine)

,usage_id,customer_id,activity_date,session_duration,feature_crm,feature_email,feature_analytics,feature_automation,feature_advanced
0,1,CUST_00001,2024-04-12,37,4,1,0,0,0
1,2,CUST_00001,2024-04-12,31,2,0,1,0,0
2,3,CUST_00001,2024-04-12,28,1,0,0,0,0
3,4,CUST_00001,2024-04-12,50,3,0,1,0,0
4,5,CUST_00001,2024-04-12,33,0,0,0,0,0

In [6]:
pd.read_sql("SELECT * FROM engagement_data LIMIT 5;", engine)

,engagement_id,customer_id,engagement_date,engagement_type,campaign_type,response_rate,responded
0,1,CUST_00001,2025-01-16,Call,Retention,0.62,1
1,2,CUST_00001,2024-12-16,In-app,Re-engagement,0.90,1
2,3,CUST_00001,2024-05-08,In-app,Onboarding,0.86,1
3,4,CUST_00001,2025-04-01,Email,Retention,0.78,1
4,5,CUST_00001,2025-11-15,Chat,Re-engagement,0.47,0

In [7]:
pd.read_sql("SELECT * FROM feedback_data LIMIT 5;", engine)

,feedback_id,customer_id,feedback_date,satisfaction_score,nps_score,feedback_category
0,1,CUST_00007,2025-06-16,7,21,Support
1,2,CUST_00011,2025-11-20,8,22,Product
2,3,CUST_00012,2025-04-25,6,19,Product
3,4,CUST_00018,2025-11-05,6,8,Features
4,5,CUST_00019,2025-11-21,8,25,Product